import Head from 'next/head'

import {FaInstagram} from 'react-icons/fa'
import {FaFacebook} from 'react-icons/fa'
import {FaLinkedin} from 'react-icons/fa'

export default function Home() {
    return (
        <>
        <Head>
            <title>Full Stack App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/images/6.png" />
        </Head>
            <div className="landing">
                <div className="landing-left">
                    <div>
                        <h1>
                            Web Design.<br />
                            Android + iOS.<br />
                            Desktop Apps.<br />
                        </h1>
                        <p>The one stop shop for all your needs.</p>
                        <FaInstagram className="icon" />
                        <FaFacebook className="icon" />
                        <FaLinkedin className="icon" />
                        <br />
                        <button className="primary-button">
                            <p>Contact Us</p>
                        </button>
                    </div>
                </div>

                <div className="landing-right">
                    <img src="/images/1.png" width="75%" />
                </div>
            </div>
            
            
            <div className="landing">
                <div className="landing-left-2">
                <img src="/images/2.png" width="75%" />
                    
                </div>

                <div className="landing-right-2">
                <div className='landing-write-2'>
                         <h1>
                            Lorem ipsum.<br />

                        </h1>
                        <div className='landing-write-5'>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                             incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis 
                             nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                              Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat
                               nulla pariatur. </p>
                               </div>
                               <div className='landing-links-1'>
                                   <p>Learn More</p>
                               </div>
            </div>
                </div>
            </div>

            
           
            
            <div className="landing">
                <div className="landing-right-2">
                <div className='landing-write-4'>
                         <h1>
                            Lorem ipsum.<br />

                        </h1>
                        <div className='landing-write-3'>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                             incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis 
                             nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                              Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat
                               nulla pariatur. </p>
                               </div>
                               <div className='landing-links-2'>
                                   <p>Learn More</p>
                               </div>
            </div>
                 
                </div>

                <div className="landing-green">
                <img src="/images/3.png" width="75%" />
                    
                </div>
            </div>

            <div className="landing">
                <div className="landing-black">
                <img src="/images/4.png" width="75%" />
                    
                </div>

                <div className="landing-right-2">
                <div className='landing-write-2'>
                         <h1>
                            Lorem ipsum.<br />

                        </h1>
                        <div className='landing-write-5'>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                             incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis 
                             nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                              Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat
                               nulla pariatur. </p>
                               </div>
                               <div className='landing-links-1'>
                                   <p>Learn More</p>
                               </div>
            </div>
                </div>
            </div>

            <div className="landing">
                <div className="landing-right-2">
                <div className='landing-write-4'>
                         <h1>
                            Lorem ipsum.<br />

                        </h1>
                        <div className='landing-write-3'>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                             incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis 
                             nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                              Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat
                               nulla pariatur. </p>
                               </div>
                               <div className='landing-links-2'>
                                   <p>Learn More</p>
                               </div>
            </div>
                 
                </div>

                <div className="landing-cyan">
                <img src="/images/5.png" width="75%" />
                    
                </div>
            </div>
            
           
            <div className="landing-lastone">
                 <div className="landing-left5">
                    <div>
                        <h1>
                        Lorem ipsum.<br />
                        </h1>
                        <p>t dolore magna aliqua. Ut enim ad minim </p>
                        <p>t dolore magna aliqua. Ut enim ad minim </p>
                        <p>t dolore magna aliqua. Ut enim ad minim </p>
                    </div>
                 </div>
             <div>
                
             </div>
             <div className='landing-port'>
             <img src="/images/6.png"  width="70%" />
             </div>
            
             </div>
             
        </>
    )
}