import Head from 'next/head'

export default function Page1() {
  return (
    <div>
      <Head>
        <title>Page 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      This is Page 1
    </div>
  )
}
