import Head from 'next/head'
import Link from 'next/link'

import Component1 from '../src/components/Component1'

export default function Page2() {
  return (
    <div>
      <Head>
        <title>My First Full Stack App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Welcome to the Home Page<br />

      <div className="landing">

      </div>

      <Component1 />
    </div>
  )
}
